dict = {
  AFN: { "Code": "Afghanistan", "Currency": "Afghani", "Symbol": "؋", "Unicode": "U+1F1E6U+1F1EB " },
  ALL: { "Code": "Albania", "Currency": "Lek", "Symbol": "Lek", "Unicode": "U+1F1E6U+1F1F1 " },
  ARS: { "Code": "Argentina", "Currency": "Peso", "Symbol": "$", "Unicode": "U+1F1E6U+1F1F7 " },
  AWG: { "Code": "Aruba", "Currency": "Guilder", "Symbol": "ƒ", "Unicode": "U+1F1E6U+1F1FC " },
  AUD: { "Code": "Australia", "Currency": "Dollar", "Symbol": "$", "Unicode": "U+1F1E6U+1F1FA " },
  AZN: { "Code": "Azerbaijan", "Currency": "Manat", "Symbol": "₼", "Unicode": "U+1F1E6U+1F1FF " },
  BSD: { "Code": "Bahamas", "Currency": "Dollar", "Symbol": "$", "Unicode": "U+1F1E7U+1F1F8 " },
  BBD: { "Code": "Barbados", "Currency": "Dollar", "Symbol": "$", "Unicode": "U+1F1E7U+1F1E7 " },
  BYR: { "Code": "Belarus", "Currency": "Ruble", "Symbol": "p.", "Unicode": "U+1F1E7U+1F1FE " },
  BZD: { "Code": "Belize", "Currency": "Dollar", "Symbol": "BZ$", "Unicode": "U+1F1E7U+1F1FF " },
  BMD: { "Code": "Bermuda", "Currency": "Dollar", "Symbol": "$", "Unicode": "U+1F1E7U+1F1F2 " },
  BOB: { "Code": "Bolivia", "Currency": "Boliviano", "Symbol": "$b", "Unicode": "U+1F1E7U+1F1F4 " },
  BAM: { "Code": "Bosnia and Herzegovina", "Currency": "Convertible Marka", "Symbol": "KM", "Unicode": "U+1F1E7U+1F1E6 " },
  BWP: { "Code": "Botswana", "Currency": "Pula", "Symbol": "P", "Unicode": "U+1F1E7U+1F1FC " },
  BRL: { "Code": "Brazil", "Currency": "Real", "Symbol": "R$", "Unicode": "U+1F1E7U+1F1F7 " },
  BND: { "Code": "Brunei", "Currency": "Darussalam Dollar", "Symbol": "$", "Unicode": "U+1F1E7U+1F1F3 " },
  BGN: { "Code": "Bulgaria", "Currency": "Lev", "Symbol": "лв", "Unicode": "U+1F1E7U+1F1EC " },
  KHR: { "Code": "Cambodia", "Currency": "Riel", "Symbol": "៛", "Unicode": "U+1F1F0U+1F1ED " },
  CAD: { "Code": "Canada", "Currency": "Dollar", "Symbol": "$", "Unicode": "U+1F1E8U+1F1E6 " },
  KYD: { "Code": "Cayman Islands", "Currency": "Dollar", "Symbol": "$", "Unicode": "U+1F1F0U+1F1FE " },
  CLP: { "Code": "Chile", "Currency": "Peso", "Symbol": "$", "Unicode": "U+1F1E8U+1F1F1 " },
  CNY: { "Code": "China", "Currency": "Yuan Renminbi", "Symbol": "¥", "Unicode": "U+1F1E8U+1F1F3 " },
  COP: { "Code": "Colombia", "Currency": "Peso", "Symbol": "$", "Unicode": "U+1F1E8U+1F1F4 " },
  CRC: { "Code": "Costa Rica", "Currency": "Colon", "Symbol": "₡", "Unicode": "U+1F1E8U+1F1F7 " },
  HRK: { "Code": "Croatia", "Currency": "Kuna", "Symbol": "kn", "Unicode": "U+1F1EDU+1F1F7 " },
  CUP: { "Code": "Cuba", "Currency": "Peso", "Symbol": "₱", "Unicode": "U+1F1E8U+1F1FA " },
  CZK: { "Code": "Czech Republic", "Currency": "Koruna", "Symbol": "Kč", "Unicode": "U+1F1E8U+1F1FF " },
  DKK: { "Code": "Denmark", "Currency": "Krone", "Symbol": "kr", "Unicode": "U+1F1E9U+1F1F0 " },
  DOP: { "Code": "Dominican Republic", "Currency": "Peso", "Symbol": "RD$", "Unicode": "U+1F1E9U+1F1F4 " },
  EGP: { "Code": "Egypt", "Currency": "Pound", "Symbol": "£", "Unicode": "U+1F1EAU+1F1EC " },
  SVC: { "Code": "El Salvador", "Currency": "Colon", "Symbol": "$", "Unicode": "U+1F1F8U+1F1FB " },
  EEK: { "Code": "Estonia", "Currency": "Kroon", "Symbol": "kr", "Unicode": "U+1F1EAU+1F1EA " },
  EUR: { "Code": "Euro Member", "Currency": "Euro", "Symbol": "€", "Unicode": "nan" },
  FKP: { "Code": "Falkland Islands", "Currency": "Pound", "Symbol": "£", "Unicode": "U+1F1EBU+1F1F0 " },
  FJD: { "Code": "Fiji", "Currency": "Dollar", "Symbol": "$", "Unicode": "U+1F1EBU+1F1EF " },
  GEL: { "Code": "Georgia", "Currency": "Lari", "Symbol": "₾", "Unicode": "U+1F1ECU+1F1EA " },
  GHC: { "Code": "Ghana", "Currency": "Cedis", "Symbol": "¢", "Unicode": "U+1F1ECU+1F1ED " },
  GIP: { "Code": "Gibraltar", "Currency": "Pound", "Symbol": "£", "Unicode": "U+1F1ECU+1F1EE " },
  GTQ: { "Code": "Guatemala", "Currency": "Quetzal", "Symbol": "Q", "Unicode": "U+1F1ECU+1F1F9 " },
  GGP: { "Code": "Guernsey", "Currency": "Pound", "Symbol": "£", "Unicode": "U+1F1ECU+1F1EC " },
  GYD: { "Code": "Guyana", "Currency": "Dollar", "Symbol": "$", "Unicode": "U+1F1ECU+1F1FE " },
  HNL: { "Code": "Honduras", "Currency": "Lempira", "Symbol": "L", "Unicode": "U+1F1EDU+1F1F3 " },
  HKD: { "Code": "Hong Kong", "Currency": "Dollar", "Symbol": "$", "Unicode": "U+1F1EDU+1F1F0 " },
  HUF: { "Code": "Hungary", "Currency": "Forint", "Symbol": "Ft", "Unicode": "U+1F1EDU+1F1FA " },
  ISK: { "Code": "Iceland", "Currency": "Krona", "Symbol": "kr", "Unicode": "U+1F1EEU+1F1F8 " },
  INR: { "Code": "India", "Currency": "Rupee", "Symbol": "₹", "Unicode": "U+1F1EEU+1F1F3 " },
  IDR: { "Code": "Indonesia", "Currency": "Rupiah", "Symbol": "Rp", "Unicode": "U+1F1EEU+1F1E9 " },
  IRR: { "Code": "Iran", "Currency": "Rial", "Symbol": "﷼", "Unicode": "U+1F1EEU+1F1F7 " },
  IMP: { "Code": "Isle of Man", "Currency": "Pound", "Symbol": "£", "Unicode": "U+1F1EEU+1F1F2 " },
  ILS: { "Code": "Israel", "Currency": "Shekel", "Symbol": "₪", "Unicode": "U+1F1EEU+1F1F1 " },
  JMD: { "Code": "Jamaica", "Currency": "Dollar", "Symbol": "J$", "Unicode": "U+1F1EFU+1F1F2 " },
  JPY: { "Code": "Japan", "Currency": "Yen", "Symbol": "¥", "Unicode": "U+1F1EFU+1F1F5 " },
  JEP: { "Code": "Jersey", "Currency": "Pound", "Symbol": "£", "Unicode": "U+1F1EFU+1F1EA " },
  KZT: { "Code": "Kazakhstan", "Currency": "Tenge", "Symbol": "лв", "Unicode": "U+1F1F0U+1F1FF " },
  KGS: { "Code": "Kyrgyzstan", "Currency": "Som", "Symbol": "лв", "Unicode": "U+1F1F0U+1F1EC " },
  LAK: { "Code": "Laos", "Currency": "Kip", "Symbol": "₭", "Unicode": "U+1F1F1U+1F1E6 " },
  LVL: { "Code": "Latvia", "Currency": "Lat", "Symbol": "Ls", "Unicode": "U+1F1F1U+1F1FB " },
  LBP: { "Code": "Lebanon", "Currency": "Pound", "Symbol": "£", "Unicode": "U+1F1F1U+1F1E7 " },
  LRD: { "Code": "Liberia", "Currency": "Dollar", "Symbol": "$", "Unicode": "U+1F1F1U+1F1F7 " },
  LTL: { "Code": "Lithuania", "Currency": "Litas", "Symbol": "Lt", "Unicode": "U+1F1F1U+1F1F9 " },
  MKD: { "Code": "Macedonia", "Currency": "Denar", "Symbol": "ден", "Unicode": "U+1F1F2U+1F1F0 " },
  MYR: { "Code": "Malaysia", "Currency": "Ringgit", "Symbol": "RM", "Unicode": "U+1F1F2U+1F1FE " },
  MUR: { "Code": "Mauritius", "Currency": "Rupee", "Symbol": "₨", "Unicode": "U+1F1F2U+1F1FA " },
  MXN: { "Code": "Mexico", "Currency": "Peso", "Symbol": "$", "Unicode": "U+1F1F2U+1F1FD " },
  MNT: { "Code": "Mongolia", "Currency": "Tughrik", "Symbol": "₮", "Unicode": "U+1F1F2U+1F1F3 " },
  MZN: { "Code": "Mozambique", "Currency": "Metical", "Symbol": "MT", "Unicode": "U+1F1F2U+1F1FF " },
  NAD: { "Code": "Namibia", "Currency": "Dollar", "Symbol": "$", "Unicode": "U+1F1F3U+1F1E6 " },
  NPR: { "Code": "Nepal", "Currency": "Rupee", "Symbol": "₨", "Unicode": "U+1F1F3U+1F1F5 " },
  ANG: { "Code": "Netherlands", "Currency": "Antilles Guilder", "Symbol": "ƒ", "Unicode": "U+1F1F3U+1F1F1 " },
  NZD: { "Code": "New Zealand", "Currency": "Dollar", "Symbol": "$", "Unicode": "U+1F1F3U+1F1FF " },
  NIO: { "Code": "Nicaragua", "Currency": "Cordoba", "Symbol": "C$", "Unicode": "U+1F1F3U+1F1EE " },
  NGN: { "Code": "Nigeria", "Currency": "Naira", "Symbol": "₦", "Unicode": "U+1F1F3U+1F1EC " },
  KPW: { "Code": "North Korea", "Currency": "Won", "Symbol": "₩", "Unicode": "U+1F1F0U+1F1F5 " },
  NOK: { "Code": "Norway", "Currency": "Krone", "Symbol": "kr", "Unicode": "U+1F1F3U+1F1F4 " },
  OMR: { "Code": "Oman", "Currency": "Rial", "Symbol": "﷼", "Unicode": "U+1F1F4U+1F1F2 " },
  PKR: { "Code": "Pakistan", "Currency": "Rupee", "Symbol": "₨", "Unicode": "U+1F1F5U+1F1F0 " },
  PAB: { "Code": "Panama", "Currency": "Balboa", "Symbol": "B/.", "Unicode": "U+1F1F5U+1F1E6 " },
  PYG: { "Code": "Paraguay", "Currency": "Guarani", "Symbol": "Gs", "Unicode": "U+1F1F5U+1F1FE " },
  PEN: { "Code": "Peru", "Currency": "Nuevo Sol", "Symbol": "S/.", "Unicode": "U+1F1F5U+1F1EA " },
  PHP: { "Code": "Philippines", "Currency": "Peso", "Symbol": "₱", "Unicode": "U+1F1F5U+1F1ED " },
  PLN: { "Code": "Poland", "Currency": "Zloty", "Symbol": "zł", "Unicode": "U+1F1F5U+1F1F1 " },
  QAR: { "Code": "Qatar", "Currency": "Riyal", "Symbol": "﷼", "Unicode": "U+1F1F6U+1F1E6 " },
  RON: { "Code": "Romania", "Currency": "New Leu", "Symbol": "lei", "Unicode": "U+1F1F7U+1F1F4 " },
  RUB: { "Code": "Russia", "Currency": "Ruble", "Symbol": "₽", "Unicode": "U+1F1F7U+1F1FA " },
  SHP: { "Code": "Saint Helena", "Currency": "Pound", "Symbol": "£", "Unicode": "U+1F1F8U+1F1ED " },
  SAR: { "Code": "Saudi Arabia", "Currency": "Riyal", "Symbol": "﷼", "Unicode": "U+1F1F8U+1F1E6 " },
  RSD: { "Code": "Serbia", "Currency": "Dinar", "Symbol": "Дин.", "Unicode": "U+1F1F7U+1F1F8 " },
  SCR: { "Code": "Seychelles", "Currency": "Rupee", "Symbol": "₨", "Unicode": "U+1F1F8U+1F1E8 " },
  SGD: { "Code": "Singapore", "Currency": "Dollar", "Symbol": "$", "Unicode": "U+1F1F8U+1F1EC " },
  SBD: { "Code": "Solomon Islands", "Currency": "Dollar", "Symbol": "$", "Unicode": "U+1F1F8U+1F1E7 " },
  SOS: { "Code": "Somalia", "Currency": "Shilling", "Symbol": "S", "Unicode": "U+1F1F8U+1F1F4 " },
  ZAR: { "Code": "South Africa", "Currency": "Rand", "Symbol": "R", "Unicode": "U+1F1FFU+1F1E6 " },
  KRW: { "Code": "South Korea", "Currency": "Won", "Symbol": "₩", "Unicode": "U+1F1F0U+1F1F7 " },
  LKR: { "Code": "Sri Lanka", "Currency": "Rupee", "Symbol": "₨", "Unicode": "U+1F1F1U+1F1F0 " },
  SRD: { "Code": "Suriname", "Currency": "Dollar", "Symbol": "$", "Unicode": "U+1F1F8U+1F1F7 " },
  SEK: { "Code": "Sweden", "Currency": "Krona", "Symbol": "kr", "Unicode": "U+1F1F8U+1F1EA " },
  CHF: { "Code": "Switzerland", "Currency": "Franc", "Symbol": "CHF", "Unicode": "U+1F1E8U+1F1ED " },
  SYP: { "Code": "Syria", "Currency": "Pound", "Symbol": "£", "Unicode": "U+1F1F8U+1F1FE " },
  TWD: { "Code": "Taiwan", "Currency": "New Dollar", "Symbol": "NT$", "Unicode": "U+1F1F9U+1F1FC " },
  THB: { "Code": "Thailand", "Currency": "Baht", "Symbol": "฿", "Unicode": "U+1F1F9U+1F1ED " },
  TTD: { "Code": "Trinidad and Tobago", "Currency": "Dollar", "Symbol": "TT$", "Unicode": "U+1F1F9U+1F1F9 " },
  TRL: { "Code": "Turkey", "Currency": "Lira", "Symbol": "₺", "Unicode": "U+1F1F9U+1F1F7 " },
  TVD: { "Code": "Tuvalu", "Currency": "Dollar", "Symbol": "$", "Unicode": "U+1F1F9U+1F1FB " },
  UAH: { "Code": "Ukraine", "Currency": "Hryvna", "Symbol": "₴", "Unicode": "U+1F1FAU+1F1E6 " },
  GBP: { "Code": "United Kingdom", "Currency": "Pound", "Symbol": "£", "Unicode": "U+1F1ECU+1F1E7 " },
  USD: { "Code": "United States", "Currency": "Dollar", "Symbol": "$", "Unicode": "U+1F1FAU+1F1F8 " },
  UYU: { "Code": "Uruguay", "Currency": "Peso", "Symbol": "$U", "Unicode": "U+1F1FAU+1F1FE " },
  UZS: { "Code": "Uzbekistan", "Currency": "Som", "Symbol": "лв", "Unicode": "U+1F1FAU+1F1FF " },
  VEF: { "Code": "Venezuela", "Currency": "Bolivar Fuerte", "Symbol": "Bs", "Unicode": "U+1F1FBU+1F1EA " },
  VND: { "Code": "Vietnam", "Currency": "Dong", "Symbol": "₫", "Unicode": "U+1F1FBU+1F1F3 " },
  YER: { "Code": "Yemen", "Currency": "Rial", "Symbol": "﷼", "Unicode": "U+1F1FEU+1F1EA " },
  ZWD: { "Code": "Zimbabwe", "Currency": "Dollar", "Symbol": "Z$", "Unicode": "U+1F1FFU+1F1FC" },
}